//! TA-Lib parity harness for `ta-indicators`.
//!
//! Ground-truth reference values are generated by
//! `scripts/gen_parity_fixtures.py` (using the local TA-Lib C extension)
//! and committed at `tests/fixtures/talib_parity.json`. Each registered entry
//! maps a fixture key to a Rust output and asserts they agree wherever TA-Lib
//! emits a (non-warmup) value.
//!
//! Policy: **warmup-exact** parity. The Rust output must match TA-Lib on every
//! bar where TA-Lib produced a value, including the warmup region.
//!
//! This file is the contract for the full TA-Lib port: a function is "done"
//! only when its fixture keys are registered here and the audit passes.
//! Regenerate the fixture with:
//!
//!     uv run --with TA-Lib --with numpy scripts/gen_parity_fixtures.py

use serde_json::Value;
use ta_indicators as ta;

const REL_TOL: f64 = 1e-6;
const ABS_TOL: f64 = 1e-6;

struct Inputs {
    open: Vec<f64>,
    high: Vec<f64>,
    low: Vec<f64>,
    close: Vec<f64>,
    volume: Vec<f64>,
    close2: Vec<f64>,
}

fn load_fixture() -> (Inputs, Value) {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/talib_parity.json"
    );
    let raw = std::fs::read_to_string(path)
        .unwrap_or_else(|err| panic!("read parity fixture {path}: {err}"));
    let root: Value = serde_json::from_str(&raw).expect("parse parity fixture json");
    let input = &root["input"];
    let series = |key: &str| -> Vec<f64> {
        input[key]
            .as_array()
            .unwrap_or_else(|| panic!("missing input series {key}"))
            .iter()
            .map(|value| value.as_f64().expect("finite input value"))
            .collect()
    };
    let inputs = Inputs {
        open: series("open"),
        high: series("high"),
        low: series("low"),
        close: series("close"),
        volume: series("volume"),
        close2: series("close2"),
    };
    (inputs, root)
}

fn expected_floats(root: &Value, key: &str) -> Vec<Option<f64>> {
    root["expected"][key]
        .as_array()
        .unwrap_or_else(|| panic!("missing expected series {key}"))
        .iter()
        .map(|value| {
            if value.is_null() {
                None
            } else {
                value.as_f64()
            }
        })
        .collect()
}

/// Compare a Rust series against the TA-Lib reference at every index where
/// TA-Lib emitted a value. Returns Ok(compared_count) or Err(first divergence).
fn check(actual: &[Option<f64>], expected: &[Option<f64>]) -> Result<usize, String> {
    if actual.len() != expected.len() {
        return Err(format!(
            "length {} != expected {}",
            actual.len(),
            expected.len()
        ));
    }
    let mut compared = 0usize;
    for (idx, exp) in expected.iter().enumerate() {
        let Some(exp) = exp else { continue };
        compared += 1;
        match actual[idx] {
            Some(got) => {
                let diff = (got - exp).abs();
                let tol = ABS_TOL + REL_TOL * exp.abs();
                if diff > tol {
                    return Err(format!(
                        "idx {idx}: got {got:.10}, expected {exp:.10} (diff {diff:.3e} > tol {tol:.3e})"
                    ));
                }
            }
            None => return Err(format!("idx {idx}: got None, expected {exp:.10}")),
        }
    }
    if compared == 0 {
        return Err("no overlapping values".to_string());
    }
    Ok(compared)
}

/// All already-ported public crate functions, mapped to their fixture keys.
fn registry(i: &Inputs) -> Vec<(&'static str, Vec<Option<f64>>)> {
    let (o, h, l, c, v, c2) = (&i.open, &i.high, &i.low, &i.close, &i.volume, &i.close2);
    let macd = ta::macd(c, 12, 26, 9);
    let macdext = ta::macdext_sma(c, 12, 26, 9);
    let mut mavp_periods = vec![14.0_f64; c.len()];
    for period in mavp_periods.iter_mut().skip(c.len() / 2) {
        *period = 30.0;
    }
    let mavp = ta::mavp(c, &mavp_periods, 2, 30);
    let cdl = |values: Vec<i32>| -> Vec<Option<f64>> {
        values.into_iter().map(|value| Some(value as f64)).collect()
    };
    let srsi = ta::stochrsi(c, 14, 5, 3);
    let adx = ta::adx_family(h, l, c, 14);
    let dm = ta::directional_movement(h, l);
    let bb = ta::bollinger_bands(c, 20, 2.0);
    let lr = ta::linear_regression(c, 14);
    let ar = ta::aroon(h, l, 14);
    let pt = ta::price_transforms(o, h, l, c);
    vec![
        ("ema_14", ta::ema(c, 14)),
        ("dema_14", ta::dema(c, 14)),
        ("tema_14", ta::tema(c, 14)),
        ("t3_5_0p7", ta::t3(c, 5, 0.7)),
        ("kama_30", ta::kama(c, 30)),
        ("trix_15", ta::trix(c, 15)),
        ("rsi_14", ta::rsi(c, 14)),
        ("cmo_14", ta::cmo(c, 14)),
        ("apo_12_26", ta::apo(c, 12, 26)),
        ("ppo_12_26", ta::ppo(c, 12, 26)),
        ("ultosc_7_14_28", ta::ultosc(h, l, c, 7, 14, 28)),
        ("bop", ta::bop(o, h, l, c)),
        ("macd_12_26_9", macd.macd),
        ("macd_signal_12_26_9", macd.signal),
        ("macd_hist_12_26_9", macd.hist),
        ("stochrsi_k_14_5_3", srsi.k),
        ("stochrsi_d_14_5_3", srsi.d),
        ("adx_14", adx.adx),
        ("adxr_14", adx.adxr),
        ("plus_di_14", adx.plus_di),
        ("minus_di_14", adx.minus_di),
        ("dx_14", adx.dx),
        ("plus_dm_1", dm.plus_dm),
        ("minus_dm_1", dm.minus_dm),
        ("bb_upper_20_2", bb.upper),
        ("bb_middle_20_2", bb.middle),
        ("bb_lower_20_2", bb.lower),
        ("linearreg_14", lr.line),
        ("linearreg_slope_14", lr.slope),
        ("linearreg_angle_14", lr.angle),
        ("linearreg_intercept_14", lr.intercept),
        ("tsf_14", lr.tsf),
        ("aroon_up_14", ar.up),
        ("aroon_down_14", ar.down),
        ("aroon_osc_14", ar.oscillator),
        ("ad", ta::ad(h, l, c, v)),
        ("adosc_3_10", ta::adosc(h, l, c, v, 3, 10)),
        ("trange", ta::trange(h, l, c)),
        ("atr_14", ta::atr(h, l, c, 14)),
        ("sar_0p02_0p2", ta::sar(h, l, 0.02, 0.2)),
        (
            "sarext_default",
            ta::sarext(h, l, 0.0, 0.0, 0.02, 0.02, 0.2, 0.02, 0.02, 0.2),
        ),
        ("sum_10", ta::rolling_sum(c, 10)),
        ("avgprice", pt.avgprice),
        ("medprice", pt.medprice),
        ("typprice", pt.typprice),
        ("wclprice", pt.wclprice),
        ("macdext_12_26_9", macdext.macd),
        ("macdext_signal_12_26_9", macdext.signal),
        ("macdext_hist_12_26_9", macdext.hist),
        ("beta_5", ta::beta(c, c2, 5)),
        ("correl_30", ta::correl(c, c2, 30)),
        ("mavp_14_30", mavp),
        ("cdldoji", cdl(ta::cdl_doji(o, h, l, c))),
        ("cdldragonflydoji", cdl(ta::cdl_dragonfly_doji(o, h, l, c))),
        (
            "cdlgravestonedoji",
            cdl(ta::cdl_gravestone_doji(o, h, l, c)),
        ),
        (
            "cdllongleggeddoji",
            cdl(ta::cdl_long_legged_doji(o, h, l, c)),
        ),
        ("cdlmarubozu", cdl(ta::cdl_marubozu(o, h, l, c))),
        (
            "cdlclosingmarubozu",
            cdl(ta::cdl_closing_marubozu(o, h, l, c)),
        ),
        ("cdllongline", cdl(ta::cdl_long_line(o, h, l, c))),
        ("cdlshortline", cdl(ta::cdl_short_line(o, h, l, c))),
        ("cdlspinningtop", cdl(ta::cdl_spinning_top(o, h, l, c))),
        ("cdlhighwave", cdl(ta::cdl_high_wave(o, h, l, c))),
        ("cdl2crows", cdl(ta::cdl_2crows(o, h, l, c))),
        ("cdl3blackcrows", cdl(ta::cdl_3blackcrows(o, h, l, c))),
        ("cdl3inside", cdl(ta::cdl_3inside(o, h, l, c))),
        ("cdl3linestrike", cdl(ta::cdl_3linestrike(o, h, l, c))),
        ("cdl3outside", cdl(ta::cdl_3outside(o, h, l, c))),
        ("cdl3starsinsouth", cdl(ta::cdl_3starsinsouth(o, h, l, c))),
        ("cdl3whitesoldiers", cdl(ta::cdl_3whitesoldiers(o, h, l, c))),
        ("cdlabandonedbaby", cdl(ta::cdl_abandonedbaby(o, h, l, c))),
        ("cdladvanceblock", cdl(ta::cdl_advanceblock(o, h, l, c))),
        ("cdlbelthold", cdl(ta::cdl_belthold(o, h, l, c))),
        ("cdlbreakaway", cdl(ta::cdl_breakaway(o, h, l, c))),
        (
            "cdlconcealbabyswall",
            cdl(ta::cdl_concealbabyswall(o, h, l, c)),
        ),
        ("cdlcounterattack", cdl(ta::cdl_counterattack(o, h, l, c))),
        ("cdldarkcloudcover", cdl(ta::cdl_darkcloudcover(o, h, l, c))),
        ("cdldojistar", cdl(ta::cdl_dojistar(o, h, l, c))),
        ("cdlengulfing", cdl(ta::cdl_engulfing(o, h, l, c))),
        (
            "cdleveningdojistar",
            cdl(ta::cdl_eveningdojistar(o, h, l, c)),
        ),
        ("cdleveningstar", cdl(ta::cdl_eveningstar(o, h, l, c))),
        (
            "cdlgapsidesidewhite",
            cdl(ta::cdl_gapsidesidewhite(o, h, l, c)),
        ),
        ("cdlhammer", cdl(ta::cdl_hammer(o, h, l, c))),
        ("cdlhangingman", cdl(ta::cdl_hangingman(o, h, l, c))),
        ("cdlharami", cdl(ta::cdl_harami(o, h, l, c))),
        ("cdlharamicross", cdl(ta::cdl_haramicross(o, h, l, c))),
        ("cdlhikkake", cdl(ta::cdl_hikkake(o, h, l, c))),
        ("cdlhikkakemod", cdl(ta::cdl_hikkakemod(o, h, l, c))),
        ("cdlhomingpigeon", cdl(ta::cdl_homingpigeon(o, h, l, c))),
        (
            "cdlidentical3crows",
            cdl(ta::cdl_identical3crows(o, h, l, c)),
        ),
        ("cdlinneck", cdl(ta::cdl_inneck(o, h, l, c))),
        ("cdlinvertedhammer", cdl(ta::cdl_invertedhammer(o, h, l, c))),
        ("cdlkicking", cdl(ta::cdl_kicking(o, h, l, c))),
        (
            "cdlkickingbylength",
            cdl(ta::cdl_kickingbylength(o, h, l, c)),
        ),
        ("cdlladderbottom", cdl(ta::cdl_ladderbottom(o, h, l, c))),
        ("cdlmatchinglow", cdl(ta::cdl_matchinglow(o, h, l, c))),
        ("cdlmathold", cdl(ta::cdl_mathold(o, h, l, c))),
        (
            "cdlmorningdojistar",
            cdl(ta::cdl_morningdojistar(o, h, l, c)),
        ),
        ("cdlmorningstar", cdl(ta::cdl_morningstar(o, h, l, c))),
        ("cdlonneck", cdl(ta::cdl_onneck(o, h, l, c))),
        ("cdlpiercing", cdl(ta::cdl_piercing(o, h, l, c))),
        ("cdlrickshawman", cdl(ta::cdl_rickshawman(o, h, l, c))),
        (
            "cdlrisefall3methods",
            cdl(ta::cdl_risefall3methods(o, h, l, c)),
        ),
        (
            "cdlseparatinglines",
            cdl(ta::cdl_separatinglines(o, h, l, c)),
        ),
        ("cdlshootingstar", cdl(ta::cdl_shootingstar(o, h, l, c))),
        ("cdlstalledpattern", cdl(ta::cdl_stalledpattern(o, h, l, c))),
        ("cdlsticksandwich", cdl(ta::cdl_sticksandwich(o, h, l, c))),
        ("cdltakuri", cdl(ta::cdl_takuri(o, h, l, c))),
        ("cdltasukigap", cdl(ta::cdl_tasukigap(o, h, l, c))),
        ("cdlthrusting", cdl(ta::cdl_thrusting(o, h, l, c))),
        ("cdltristar", cdl(ta::cdl_tristar(o, h, l, c))),
        ("cdlunique3river", cdl(ta::cdl_unique3river(o, h, l, c))),
        (
            "cdlupsidegap2crows",
            cdl(ta::cdl_upsidegap2crows(o, h, l, c)),
        ),
        (
            "cdlxsidegap3methods",
            cdl(ta::cdl_xsidegap3methods(o, h, l, c)),
        ),
    ]
}

/// Regression gate: every registered series must match TA-Lib warmup-exact.
#[test]
fn existing_coverage_matches_talib() {
    let (i, root) = load_fixture();
    let mut failures: Vec<String> = Vec::new();
    let mut pass = 0usize;
    println!("\n=== TA-Lib parity gate (existing coverage) ===");
    for (name, actual) in registry(&i) {
        match check(&actual, &expected_floats(&root, name)) {
            Ok(n) => {
                pass += 1;
                println!("  PASS  {name:<24} ({n} bars)");
            }
            Err(msg) => {
                println!("  FAIL  {name:<24} {msg}");
                failures.push(format!("{name}: {msg}"));
            }
        }
    }
    println!("=== {pass} pass, {} fail ===\n", failures.len());
    assert!(
        failures.is_empty(),
        "TA-Lib parity divergences:\n{}",
        failures.join("\n")
    );
}
